apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-store-ingress
  namespace: demo
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - aks-store.local
      secretName: aks-store-tls

  rules:
  - http:
      paths:

      - path: /
        pathType: Prefix
        backend:
          service:
            name: store-front
            port:
              number: 80

      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: store-admin
            port:
              number: 80
