apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aks-store-demo
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://github.com/gunjankapoor99/Azure-DevOps-Platform.git
    targetRevision: develop
    path: helm/aks-store-demo

    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
